### ISSUE TITLE
[Feature request] Ability to edit giveaways

### ISSUE THREAD

**Issue by KimPlayz4LK** [jagrosh/GiveawayBot#100] opened 2021-08-14 20:24 UTC
Hi! I would like to have the ability to edit giveaways, like i misspelled or forgot to add something, and there is no way to edit it.
Example: g!edit <mesage id of the giveaway> <thing to edit, like name or winner count> <value>
Example: g!edit 1234567890 name 100$ dollars

**Comment by KimPlayz4LK** [comment] 2021-08-14 20:25
My issue number is #100, i hope you will add this 100% lol

**Comment by KimPlayz4LK** [comment] 2021-08-14 20:34
Oh actually nevermind
Sorry haven't checked for existing suggestions #58

**Comment by jagrosh** [comment] 2021-12-24 02:33
Duplicate of #58

**Closed by jagrosh** 2021-12-24 02:33 UTC
Labels: duplicate
