### ISSUE TITLE
Be able to leave a giveaway

### ISSUE THREAD

**Issue by Nzii3** [jagrosh/GiveawayBot#159] opened 2022-06-03 14:46 UTC
If a user is already entered into a giveaway, if they press the button to enter the giveaway, it should remove the user's entry, because a user might not want to be entered into the giveaway anymore. It would basically be a toggle of entering a giveaway.

**Comment by jagrosh** [comment] 2022-06-03 14:48
Duplicate of #149

**Closed as completed by jagrosh** 2022-06-03 14:48 UTC
