### ISSUE TITLE
Duplicate of #162

### ISSUE THREAD

**Issue by TrulyLife420** [jagrosh/GiveawayBot#189] opened 2022-08-20 20:24 UTC
Duplicate of #162

_Originally posted by @jagrosh in https://github.com/jagrosh/GiveawayBot/issues/188#issuecomment-1221401710_

This was not a duplicate!

**Comment by TrulyLife420** [comment] 2022-08-20 20:25
You can actually see I just made this account and that was my first post!

**Comment by jagrosh** [comment] 2022-08-20 20:26
The title of the post (`Won't show who enters the giveaways now!`) is a duplicate of the feature request `View current entrant list while giveaway is running`. Please do not open new issues to comment on other issues; you can comment on the existing issue.

**Closed by jagrosh** 2022-08-20 20:26 UTC
