### ISSUE TITLE
Adding Cover Images to Giveaways

### ISSUE THREAD

**Issue by Andyman-can** [jagrosh/GiveawayBot#144] opened 2022-03-28 04:20 UTC
Feature Request - Please add a way to upload an image or a Imgur.com image address link to each giveaway.  This way, discord members can obtain more info on the giveaway prize.

**Comment by jagrosh** [comment] 2022-03-28 04:22
Duplicate of #36

**Closed by jagrosh** 2022-03-28 04:22 UTC

**Comment by mgdno2024** [comment] 2022-03-28 16:58
0x92D2057B908320352DD34c1769FD4e3E6E75C72f
