### ISSUE TITLE
Ping host when the giveaway ends

### ISSUE THREAD

**Issue by soulusz** [jagrosh/GiveawayBot#258] opened 2023-10-04 02:03 UTC
Due to the fact you're not being notified as the host when a giveaway ends, it makes you forget about it sometimes. It would be great to have a feature that also pings the host.

**Comment by DucDuyGaming** [comment] 2023-10-04 10:56
i believe this is a duplicate of #115

**Closed** 2023-10-04 14:54 UTC
