### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ItzAarushYT** [jagrosh/GiveawayBot#167] opened 2022-06-15 09:36 UTC
change the giveaway enter style. Replace the reaction to enter to click button to enter, Buttons just look better and add an feature so that the host can select the emoji of the giveaway. Like instead of 🎉 it could be 😄 or anything.

**Comment by jagrosh** [comment] 2022-06-15 13:47
Duplicate of #145

**Closed by jagrosh** 2022-06-15 13:47 UTC
