### ISSUE TITLE
[Feature Request] Ability to add image when creating a giveway

### ISSUE THREAD

**Issue by stschuette** [jagrosh/GiveawayBot#220] opened 2022-12-11 18:38 UTC
# Feature Request
Ability to add an an image/file along with, or instead of the description when creating the giveaway

### Scenario
I help run a discord server for an MMO-RPG guild. When doing giveaways related to the game(s), it often involves items from within the game(s). So once the giveaway is created, a screenshot of the item is usually added after the giveaway post to allow participants to see what it looks like if they are not currently in the game.

**Comment by jagrosh** [comment] 2022-12-14 15:39
Duplicate of #36

**Closed by jagrosh** 2022-12-14 15:39 UTC
