### ISSUE TITLE
Won't show who enters the giveaways now!

### ISSUE THREAD

**Issue by TrulyLife420** [jagrosh/GiveawayBot#188] opened 2022-08-20 20:09 UTC
I am having my whole community complain to me about this and it is also bothering me that I don't even want to do giveaways until it shows who's entered because some people either enter multiple times now or not in at all. I was trying to get in touch with Someone who could help the first guy told me it's not broken and it should work. That was what he said and he said it is what it is. Then the next guy was actually helping me then this Read About Me tells me F**k you in your discord server. I was just trying to get help it's frustrating that when you enter you can't get the owner via ping and you can't privately message him because he has a rule against that!

So hard to get help there only one person was being respectful to me as I am trying to figure out why it's messing up I get told F**k You! By Read About Me!

This is very professional and how staff should be to members looking for help!
![Screenshot_20220820-153335](https://user-images.githubusercontent.com/111660178/185764433-1c38a67e-1698-4015-9be9-88901a3f24c1.png)

**Comment by TrulyLife420** [comment] 2022-08-20 20:10
This is how to be professional these days then I'm not there yet I have some self control with my cussing! I don't tell anyone that I am here to help Fu*k You!

**Comment by jagrosh** [comment] 2022-08-20 20:20
Duplicate of #162

**Closed by jagrosh** 2022-08-20 20:20 UTC

**Comment by jagrosh** [comment] 2022-08-20 20:28
The functionality you're describing here (seeing the current entrants before the giveaway ends) is already being tracked in the issue I linked.

For issues related to the Discord server and not the bot, please make contact via Discord. This GitHub repository is only for tracking issues with the bot itself.

**Comment by TrulyLife420** [comment] 2022-08-20 20:33
I'll just get disrespected by Read My About Me
And his power tripping entitled self!

**Comment by jagrosh** [comment] 2022-08-20 20:35
Issues between Discord users are not related to the bot's code. Please do not use the GitHub repository to discuss problems with a Discord server or user; you can DM an admin or a moderator if you have a problem with a user.

**Comment by TrulyLife420** [comment] 2022-08-20 20:37
Well your owner and everyone needs to know so I posted it my bad brother he
muted me so I can't talk in your discord so that's why it's here thanks for
understanding bub

**Comment by jagrosh** [comment] 2022-08-20 20:38
I never disable DMs, so there is always at least one staff member available to DM (even if it may take a while to get a response).

**Comment by TrulyLife420** [comment] 2022-08-20 20:38
Your the owner can you please talk to him that was uncalled for regardless
of circumstances you don't talk like that.

**Comment by jagrosh** [comment] 2022-08-20 20:38
Feel free to reach out over Discord DMs if you'd like to discuss this.

**Comment by TrulyLife420** [comment] 2022-08-20 20:39
Your rules say not to dm bruhh

**Comment by TrulyLife420** [comment] 2022-08-20 20:39
Dms to you?

**Comment by jagrosh** [comment] 2022-08-20 20:41
There are no rules against sending normal DMs. There is a rule about not advertising, which mentions that you are not allowed to advertise in DMs, but that's only specific to advertising.
