### ISSUE TITLE
Raconsider the 1st suggestion of #199

### ISSUE THREAD

**Issue by GodlyFirecracker** [jagrosh/GiveawayBot#241] opened 2023-05-26 04:09 UTC
Maybe I really want to know how many losers are there in there,why would it be not planned,it's kinda useful as it Is not possible to see giveaway summary while giveaway is running,also when giveaway ends,it will show entrants instead of losers
Also losers should show when amount of entrants exceeds winners

**Comment by bup0441** [comment] 2023-05-26 04:19
As said before, it's not gonna be added. There doesn't seem to be any point to listing people who lose the giveaway. You can't see who will lose *while the giveaway is running* and again, it seems rather unhelpful to all involved to list "the losers" instead of just winners and total entrants.

**Comment by jagrosh** [comment] 2023-05-27 01:05
Duplicate of #199

**Closed by jagrosh** 2023-05-27 01:05 UTC
