### ISSUE TITLE
Would like to see list of entrants before giveaway ends

### ISSUE THREAD

**Issue by AuricSeagard** [jagrosh/GiveawayBot#229] opened 2023-02-04 04:21 UTC
Hi! I would like to be able to see the list of entrants in a giveaway before the giveaway is rolled so that I can confirm if someone has entered. It might also be useful to have the ability to remove someone from the entrant list before the giveaway is rolled, if they become ineligible.

**Comment by 11naman** [comment] 2023-02-04 04:36
Somewhat suplicate of #162. Viewing entrant list while a giveaway is running is not possible due to reasons. Refer to 162 for more details.
Secondly, although they developer is working on figuring out a good way to implement 162, *removing* entrants from a giveaway will still *never* be possible. It was possible earlier on with reactions, because it couldn't not be. Anyone who sees a giveaway must be able to enter it, thus entrant moderation is not allowed in this bot.

**Comment by JetCrooked** [comment] 2023-02-04 04:37
Duplicate of #162.

Seriously, how hard is it to look through existing issues before making one?

**Comment by JetCrooked** [comment] 2023-02-04 04:47
and...I didn't read n11's comment before posting mine, so it seems I'm a hypocrite here 💀

**Comment by jagrosh** [comment] 2023-03-29 21:05
Dupe of #162 as already mentioned

**Closed by jagrosh** 2023-03-29 21:05 UTC
