### ISSUE TITLE
[Feature Request] Add rerolled winners to giveaway embed

### ISSUE THREAD

**Issue by MertBhey** [jagrosh/GiveawayBot#216] opened 2022-11-06 11:18 UTC
Giveaway summary and the giveaway message is not updating when the giveaway is rerolled.

![discord-ss](https://user-images.githubusercontent.com/41897689/200167477-7fa5ee08-254e-477e-b9c2-ae11a089cb0c.png)
![gwbot-page-ss](https://user-images.githubusercontent.com/41897689/200167493-04a04445-e8d2-42a4-bcde-c9ac4840d8b9.png)

**Comment by jagrosh** [comment] 2022-11-06 18:35
The giveaway summary cannot be edited once it exists, as it is a static file.

Adding rerolled winners to the original embed is feasible.

**Comment by jagrosh** [comment] 2022-11-06 18:37
Just realized this is a duplicate of #156

**Closed by jagrosh** 2022-11-06 18:37 UTC
Labels: enhancement
