### ISSUE TITLE
Routine Giveaways & A Few Suggestions

### ISSUE THREAD

**Issue by flimedime** [jagrosh/GiveawayBot#212] opened 2022-10-28 19:33 UTC
**Hello, below are a few requests of mine.**

- The bot should have the option to create a reoccurring giveaway based on seconds. So, for example, if one would like the bot to start a new giveaway every 64 seconds, it would do that with the same template.

- The bot should also be able to have a command to modify any current active giveaway.

- The bot should have the option to end giveaways after a set amount of entries. So, for example, if one sets the maximum number of entries to 8, a winner will be declared after the eighth entry; otherwise, the giveaway remains open for the rest of the allotted time.

- Make the entry button disappear after entering a giveaway, replace it with a leave giveaway button, and let the user know whether they are participating.

These are just some ideas.

**Comment by jagrosh** [comment] 2022-11-06 18:40
- Automated giveaways are not going to be added, as each instance of the bot performing an action should be triggered by a  human (guidelines from Discord's developer rules). Scheduled giveaways are planned, and #96 would be a better way to run the same giveaway multiple times; it would still require human input but not very much.
- Duplicate of #141, #58 
- Duplicate of #97, or at least basically the same thing, just the other half of the feature
- Not possible, every user sees the same button and it can't be changed for just one user. If Discord supported something like this, I would use it.

**Closed by jagrosh** 2022-11-06 18:40 UTC
