### ISSUE TITLE
Pinging Host when Announcing Winners

### ISSUE THREAD

**Issue by hanseworld** [jagrosh/GiveawayBot#266] opened 2023-12-10 19:52 UTC
I think it would be very beneficial if you had the option to have the bot ping the person who hosted the giveaway when it pings the people who won! Oftentimes, when I host a giveaway I will forget about it and not realize it ended, as I didn't get pinged!

**Comment by jagrosh** [comment] 2023-12-10 20:26
Duplicate of #115

**Closed by jagrosh** 2023-12-10 20:26 UTC
